#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'commander'
require_relative 'lib/workflow'

class DSW
  include Commander::Methods

  def run
    program :name, 'dsw'
    program :version, '0.1.0'
    program :description, 'Deep Seq experiments post-processing workflow'

    command :forbid do |c|
      c.syntax = 'dsw forbid [options]'
      c.summary = ''
      c.description = 'Revokes all permission to all the completed runs or the specified rundir'
      #c.example 'description', 'command example'
      c.option '--rundir DIR', String, 'acts only on the specified absolute path'
      c.action do |args, options|

        options.default rundir: nil

        if options.rundir.nil?
          Workflow.start(:forbid)
        else
          manager = Workflow.select_manager(options.rundir)
          manager.forbid! unless Workflow.remove_dir_if_empty(manager)
        end

      end
    end

    command :archive do |c|
      c.syntax = 'dsw archive [options]'
      c.summary = ''
      c.description = 'Calls the initial step of the workflow.'
      #c.example 'description', 'command example'
      c.option '--rundir DIR', String, 'acts only on the specified directory'
      c.action do |args, options|

        options.default rundir: nil

        if options.rundir.nil?
          Workflow.start(:archive)
        else
          manager = Workflow.select_manager(options.rundir)
          manager.run_from(:archive) unless Workflow.remove_dir_if_empty(manager)
        end

      end
    end

    command :duplicity do |c|
      c.syntax = 'dsw duplicity [options]'
      c.summary = ''
      c.description = 'Calls the duplicity backup subroutine, attempting to add another incremental backup.'
      c.option '--rundir DIR', String, 'acts only on the specified directory'
      c.option '--singlestep', 'if specified does not progress with the workflow but just makes the remote backup instead'
      c.action do |args, options|

        options.default rundir: nil

        if options.rundir.nil?
          Workflow.start(:duplicity)
        else
          if options.singlestep
            manager = Workflow.select_manager(options.rundir)
            manager.run_from(:duplicity, {single_step: true}) unless Workflow.remove_dir_if_empty(manager)
          else
            manager = Workflow.select_manager(options.rundir)
            manager.run_from(:duplicity) unless Workflow.remove_dir_if_empty(manager)
          end
        end

      end
    end

    command :filter_data do |c|
      c.syntax = 'dsw filter_data [options]'
      c.summary = ''
      c.description = ''
      c.option '--rundir DIR', String, 'acts only on the specified directory'
      c.action do |args, options|

        options.default rundir: nil

        if options.rundir.nil?
          Workflow.start(:filter_data)
        else
          manager = Workflow.select_manager(options.rundir)
          manager.run_from(:filter_data) unless Workflow.remove_dir_if_empty(manager)
        end

      end
    end

    command :demultiplex do |c|
      c.syntax = 'dsw demultiplex [options]'
      c.summary = ''
      c.description = 'Calls the demultiplexing subroutine (bcl2fastq).'
      c.option '--rundir DIR', String, 'acts only on the specified directory'
      c.action do |args, options|

        options.default runname: nil

        if options.runname.nil?
          say "you need to specify --runname value"
        else
          dest_dir = File.join(Conf.global_conf[:restore_dir], options.runname)
          manager = Workflow.select_manager(dest_dir)
          manager.run_from(:restore!)
        end

      end
    end

    command :restore do |c|
      c.syntax = 'dsw restore [options]'
      c.summary = ''
      c.description = 'Calls the restore routine to retrieve old backups from the tape archive.'
      c.option '--runname DIR', String, 'fetches the run dir for the specified run name'
      c.action do |args, options|

        options.default runname: nil

        if options.runname.nil?
          say "you need to specify a --runname value."
        else
          Sequencer.restore!(run_name: options.runname)
        end

      end
    end

  run!
  end
end

DSW.new.run if $0 == __FILE__
